### ISSUE TITLE
Relaterte planer resultat - kun en relatert plan tillatt

### ISSUE THREAD

**Issue by scalerow** [ks-no/fiks-plan-specification#1]
Planrelasjoner er satt til å være ett objekt, burde vært ett array for å tillate flere relasjoner i resultatet

**Comment by scalerow** [comment]
https://github.com/ks-no/fiks-plan-specification/pull/2

**Comment by jarleborsheim** [comment]
Hei! Jeg har sett over pull-request og det ser greit ut. Det ble litt vanskelig å følge endringene i diff visningen på github. Vi går gjennom dette i møtet 21.09.22 og får det spikret da.

**Comment by jarleborsheim** [comment]
Stenger denne da den er merget inn 👍
