### ISSUE TITLE
Trekke ut flere felles komponenter i eget skjema

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#21]
Tilsvarende slik det har blitt gjort for nasjonalArealplanId.

**Comment by jarleborsheim** [comment]
Ting oppdaget underveis med arbeidet:
## Arealplan
`no.ks.fiks.plan.v2.innsyn.relaterteplaner.hent.resultat.schema.json` hadde "forslagstillerType" som required. Det hadde ikke `no.ks.fiks.plan.v2.innsyn.planerforadresse.finn.resultat.schema.json`. Hva skal vi velge?

**Comment by jarleborsheim** [comment]
Nytt spørsmål fra en som ikke kan terminologien godt nok :)

Er `plan` og `arealplan` egentlig det samme? Vi har noen meldingstyper som nevner **arealplan** som en enhet, f.eks. 
`no.ks.fiks.plan.v2.innsyn.arealplan.hent.schema.json` mens andre som bruker **plan** som en enhet i meldingstypen som f.eks. `no.ks.fiks.plan.v2.innsyn.planer.finn.schema.json`. 

Når jeg ser inne i skjemaene er det litt blandet hva som er brukt hvor. Meldingstypen `no.ks.fiks.plan.v2.innsyn.planerforadresse.finn.resultat.schema.json` hadde datatypen Arealplan definert i definitions men har "plan" i navnet og returnerer et array med "planer". Litt miks altså.

Og når jeg ser på definisjon av `Plan` og `Arealplan` som datatyper ser de jo veldig like ut. Jeg har nå trukket ut `Arealplan` i eget skjema og referert det der det var 100% arealplan i navn og type. Men kan jeg da også bruke "Arealplan" der det står plan i skjema/meldingstyper? Evt rename fellestypen til plan hvis det er "supertypen" og arealplan er en undertype av plan.

**Comment by jarleborsheim** [comment]
### Posisjon
Har trukket denne ut som egen da den var i bruk flere steder. Men så ser jeg at den hadde "description" satt til "Punkt", og i Fiks-Arkiv standarden finne det noe som heter Punkt, men ikke med så mange felter. Er det egentlig samme ting i Fiks-Plan og Fiks-Arkiv og burde hete det samme?

**Comment by sturtzel** [comment]
Punkt/posisjon/koordinat inngår flere steder. Prøver å finne definisjonen i Plan og så da at no.ks.fiks.plan.v2.innsyn.bboxforplan.hent.resultat.schema.json opererer med string for to punkter (i tillegg til koordinatsystem). I no.ks.fiks.plan.v2.innsyn.planerforomraade.finn.schema.json er det definert omraade som også angis ved hjelp av koordinater. 
@jarleborsheim  Hvor var det du fant definisjonen med flere felt enn den i arkiv?

**Comment by jarleborsheim** [comment]
Fiks-Arkiv (arkivmelding.xsd):
```
 <xs:complexType name="punkt">
        <xs:sequence>
            <xs:element name="koordinatsystem" type="n5mdk:koordinatsystem"/>
            <xs:element name="x" type="n5mdk:x"/>
            <xs:element name="y" type="n5mdk:y"/>
            <xs:element name="z" type="n5mdk:z" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
```

Nå blir det kanskje lettere å sammenlikne mot det arbeidet jeg gjør i egen branch hvor jeg trekker ut felles objekter i egne felles skjema. Her er Posisjon som er trukket ut av Dispensasjon og Planbehandling (som er også nye felles typer trukket ut av skjema): https://github.com/ks-no/fiks-plan-specification/pull/23/files#diff-a8360d594a822db4f11c06c4a0adebf40b224ad8e102c74ebc8eaa5668ef28c0

Det jeg ser er at den er litt annerledes enn Fiks-Arkiv med at den har `type`, `koordinater` og `crs`

**Comment by sturtzel** [comment]
Type er enum med kun Point som mulighet. Hva er tenkt ellers?
Crs (Coordinate Reference System)  og koordinatsystem er det samme.
Koordinater er et array med minst to elementer. Å angi x og y er (og evt. z) betyr at man slipper å forklare rekkefølgen på items.

Innholdsmessig er de to like gitt at det ikke kommer en annen type posisjon enn punkt. Arkiv har valgt norske navn.

**Comment by jarleborsheim** [comment]
For omraade i `no.ks.fiks.plan.v2.innsyn.midlertidigforbud.sjekk.resultat.schema.json` så fant jeg "Polygon" som verdi i type: 
```
"omraade": {
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "Polygon"
                            ]
                        },
```

**Comment by sturtzel** [comment]
Polygon er et sett av Punkt, men med felles koordinatsystem. Så det kan være fornuftig å lage to basisobjekter, koordinatsystem og koordinat. Da kan punkt ha disse to, mens polygon kan ha koordinatsystem og et array av koordinat.
