### ISSUE TITLE
Diskutere noen flere meldingsnavn

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#24]
Det kan argumenteres for at meldingstypen `no.ks.fiks.plan.v2.innsyn.planerforadresse.finn.schema.json` burde hete noe mer i retning av `no.ks.fiks.plan.v2.innsyn.arealplaner.for.adresse.finn.schema.json` eller `no.ks.fiks.plan.v2.innsyn.arealplaner.finn.for.adresse.schema.json`. 
Dette fordi det kan kanskje sees på som en annen variant av `no.ks.fiks.plan.v2.innsyn.arealplaner.finn.schema`?
Begge returnerer jo liste med `arealplaner`. Med mindre det er noe domene spesifikk begrunnelse for at det heter slik. 

Det samme gjelder forsåvidt også disse meldingene: 

- `no.ks.fiks.plan.v2.innsyn.planerformatrikkelenhet.finn.schema.json`
- `no.ks.fiks.plan.v2.innsyn.planerforomraade.finn.schema.json`

**Comment by jarleborsheim** [comment]
Dette gjelder også` no.ks.fiks.plan.v2.oppdatering.dispensasjonplan.registrer.schema.json` som skal renames til dispensasjon.registrer

**Comment by sturtzel** [comment]
Det bør være konsistent navngivning, men ikke lag setninger (innsyn.arealplaner.for.adresse.finn), kutt i det minste ut leddet .for.

Evt. reduser antall tjenestekall og la det være valgfritt inni kallet om det angis matrikkelenhet, areal, adresse, ... D.v.s. at vi kun har innsyn.arealplaner.finn.

**Comment by sturtzel** [comment]
Ja, det blir en prinsippdiskusjon om man skal lage en ny tjeneste for hver "where" eller om man skal ha en generell søketjeneste som for Fiks arkiv. Om man bare forholder seg til et bibliotek er det nok enklere med spissede kall, men da kan det fort bli svært mange. Jeg synes derfor at det holder med arealplaner.finn og så kan payload være varianter som adresse, matrikkelnummer, areal/punkt, tidsrom, forslagsstiller, status eller hva annet man kunne tenke seg å spørre på bakgrunn av.

**Comment by jarleborsheim** [comment]
Jeg kan lage et forslag hvor vi slår det sammen. Men se også issue #30 mtp at resultat skjema for 2 av disse finn meldingene ser litt rare ut og skiller seg ut fra resten.

**Comment by jarleborsheim** [comment]
Vi kan "merge" alle finn.for arealplan resultat meldinger til 1 resultat melding siden de er like
