### ISSUE TITLE
Burde Posisjon og Omraade følge GeoJson standarden?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#26]
### Dokumentasjon
RFC: https://www.rfc-editor.org/rfc/rfc7946
Wikipedia: https://en.wikipedia.org/wiki/GeoJSON
Eksempler osv: https://doc.arcgis.com/en/arcgis-online/reference/geojson.htm#ESRI_SECTION1_FEA94048ECD24DDD96F24604D6DEFAEA

**Comment by gunstein** [comment]
Dokumentene du refererer til er fine.
Ellers om GeoJSON:
- Foreslår at vi bruker default SRS, WGS84, i starten. Hvis det ikke dekker behovet så får vi ble enige om en måte å spesifisere SRS.
- Foreslår også at det ikke genereres noen klasser for GeoJSON, men at GeoJSON legges i en streng og at det beskrives at denne strengen må følge GeoJSON-standarden. Det finnes mange bibliotek for å validere og serialisere GeoJSON.

**Comment by sturtzel** [comment]
GeoIntegrasjon har angivelse av koordinatsystem.
Hva brukes i matrikkelen?
Hva brukes i generelle tjenester fra Kartverket m.fl.
Hva brukes i dagens planregistre?
Hvis alle forholder seg til WGS84 er det ikke noe problem. Vi bør ikke innføre noe i Fiks Plan som kolliderer med andre tjenesteområder uten at disse håndteres samtidig.

**Comment by jarleborsheim** [comment]
I stedet for å ha GeoJson som en streng i posisjon og omraade objektene, så kunne vi vurdere å ta med GeoJson som et vedlegg, altså en egen fil som følger med payloaden til meldingen. 
Den kan vi da kreve at følger. GeoJson standarden og eventuelt de json schemas som GeoJson standarden har: https://github.com/geojson/schema

**Comment by jarleborsheim** [comment]
Vi lander på at vi nå sier at det er WGS84 som gjelder.
Dette må dokumenteres at er det som skal brukes og vi kan ta vekk crs i posisjon og omraade
