### ISSUE TITLE
Valideringsfeil melding?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#29]
Fant referanse til feilmeldingen` no.ks.fiks.plan.oppdatering.valideringsfeil.v2` i dokumentasjonen/wiki.
Men den er ikke definert som skjema noe sted.
Likner den de andre feilmeldingene som f.eks. for ugyldigforespørsel og skal være lik utforming mtp skjema?

**Comment by gunstein** [comment]
I ugyldigforespørsel feilmeldingen har man mulighet til å spesifisere nærmere i feilmeldingsteksten.
Tenker det holder og at man kan droppe no.ks.fiks.plan.oppdatering.valideringsfeil.v2.

**Comment by jarleborsheim** [comment]
Supert. Jeg er enig. Da endrer jeg det i dokumentasjonen til at man skal benytte seg av ugyldigforespørsel 👍

**Comment by jarleborsheim** [comment]
Stenger denne da dokumentasjon er oppdatert
