### ISSUE TITLE
Søkeresultat som returnerer både resultat og søkekriterie?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#30]
Jeg ser at resultat skjema for å finne arealplan basert på adresse og matrikkelenhet er definert som at man skal returnerer søkekriteriet tilbake. Er det nødvendig?  [no.ks.fiks.plan.v2.innsyn.arealplaner.finn.for.adresse.resultat.schema.json](https://github.com/ks-no/fiks-plan-specification/blob/main/Schema/V2/no.ks.fiks.plan.v2.innsyn.arealplaner.finn.for.adresse.resultat.schema.json) og [no.ks.fiks.plan.v2.innsyn.arealplaner.finn.for.matrikkelenhet.resultat.schema.json](https://github.com/ks-no/fiks-plan-specification/blob/main/Schema/V2/no.ks.fiks.plan.v2.innsyn.arealplaner.finn.for.matrikkelenhet.resultat.schema.json)

I tillegg er kun adresse satt som required og ikke resultatet. Er det bare en copy/paste feil?

**Comment by sturtzel** [comment]
Sammenligner med arealplaner for område. Der er det kun arealplaner i resultat.

Jeg ser ikke behovet for å angi søkekriteriene. De som trenger å ta vare på disse bør gjør dette lokalt. De må uansett knytte resultatet til forespørselen via f.eks. klientMeldingId fra Fiks IO.

**Comment by jarleborsheim** [comment]
Nei, jeg tenker det samme. Det virker unødvendig.

**Comment by gunstein** [comment]
Enig, virker unødvendig å returnere søkekriteriet.

**Comment by jarleborsheim** [comment]
Ja, resultatet bør være required. Det fikser jeg i samme PR 👍

**Comment by jarleborsheim** [comment]
Stenger da vi har merget inn en fiks
