### ISSUE TITLE
Finn plandokumenter forbedringer 

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#32]
Ref diskusjon på Slack:

> Sitter med Finn plandokumenter: https://github.com/ks-no/fiks-plan-specification/blob/main/Schema/V2/no.ks.fiks.plan.v2.innsyn.plandokumenter.finn.schema.json
For å hente ut plandokumenter må man idag inn med saksnummer, jeg/vi(Norkart) mener det hadde vært bedre å sende inn nasjonalarealplanid her - åpen for at vi har oversett noe 🙂 

Og:

> Vi har diskutert litt her nå - Finn plandokumenter vil kanskje bli litt for generell dersom du henter den med nasjonalarealplanid.
På en annen side så har ikke vi noe krav om saksnummer på hverkan arealplan eller på behandlinger, så den vil også potensielt kunne gi mangelfulle svar.
Vårt forslag til løsning er at man tilføyer plandokument-typen til de tre store fellestypene; felles.arealplan, felles.planbehandling og felles.dispensasjon, for å sikre at dokumentet har en tydelig tilhørighet. På den måten så kan man da kanskje også droppe "endepunktet" plandokumenter.finn.
Kanskje lurt å diskutere dette i møtet på onsdag?

**Comment by jarleborsheim** [comment]
Vi tar bort finn.plandokumenter og heller legger til inkluder valg i hent.arealplan og at plandokumenter er optional type i areaplan, planbehandling og dispensasjon. 
Dvs inkluder skal inn i hent.arealplan, hent.dispensasjon. og hent.planbehandling. 
Inkluder er en string og enum som foreløpig har "plandokumenter" som valg

**Comment by jarleborsheim** [comment]
Vi bør utvide referanseDokumentfil til å være enten en url eller en referanse som kan brukes for å hente filen

**Comment by jarleborsheim** [comment]
Det er ikke noen hent.dispensasjon eller hent.planbehandling meldinger definert nå. Er det en mangel eller var tanken at vi skulle legge inn plandokumenter som et optional objekt(er) i resultatet på finn.dispensasjon og finn.planbehandling?

Videre lurer jeg på om liste med `plandokumenter` skal være som en liste ved siden av `arealplan` og `planbehandlinger` i resultat meldingen (se under) eller om det skal være i selve arealplan objektet:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "no.ks.fiks.plan.v2.innsyn.arealplan.hent.resultat.schema.json",
    "title": "HentArealplanResultat",
    "type": "object",
    "properties": {
        "arealplan": {
            "$ref": "no.ks.fiks.plan.v2.felles.arealplan.schema.json"
        },
        "planbehandlinger": {
            "type": "array",
            "items": {
                "$ref": "no.ks.fiks.plan.v2.felles.planbehandling.schema.json"
            }
        },
        "plandokumenter": {
            "type": "array",
            "items": {
                "$ref": "no.ks.fiks.plan.v2.felles.dokument.schema.json"
            }
        }
    }
}
```

**Comment by sturtzel** [comment]
Jeg tror det kan holde med finn-tjenestene foreløbig. Så får vi se om det blir for mye data og at man derfor ønsker mindre data i finn og så en hent for å få med alt. Men da må nok plandokumenter være med i resultatet. Ellers trengs henttjeneste.

For arealplaner er det mange dispensasjoner og mange behandlinger. Summen av antall dokumenter blir derfor høy. For en enkelt dispensasjon eller behandling vil nok dokumentmengden være overkommelig.

**Comment by jarleborsheim** [comment]
Ok. Den er grei. Men skal plandokumenter være en liste i resultat-meldingen eller ligge som en liste i `dispensasjon` og `planbehandling` objektet (altså de skjemaene som er skilt ut)?
