### ISSUE TITLE
DispensasjonType i dispensasjon

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#52]
Som diskutert i møtet 24.05.2023 kom vi fram til følgende:
- Det bør dokumenteres i wiki at kodelisten er henhold til spec fra KS for e-byggesak når det gjelder dispensasjon fra Arealplan
- Dette bør også så i description felt i skjema for dispensasjon

https://www.ks.no/fagomrader/digitalisering/felleslosninger/verktoykasse-plan--og-byggesak/verktoy/nasjonal-produktspesifikasjon-plan--og-byggesak/

**Comment by sturtzel** [comment]
DispensasjonType er i henhold til PlanDispensasjonType i KS' produktspesifikasjon (ref. figur 42, side 145).

D.v.s. at koder som ikke gjelder plan i DispensasjonType i SOSI produktspesifikasjon ikke skal brukes.

Feltet dispensasjonstype i KS' produktspesifikasjon vil alltid være PLAN (Arealplaner) for dispensasjoner som registreres i og hentes fra planregisteret.
