### ISSUE TITLE
Manglende skjema-filer

### ISSUE THREAD

**Issue by oyei** [ks-no/fiks-plan-specification#80]
https://github.com/ks-no/fiks-plan-specification/wiki/Brukstilfelle-Finn-plandokumenter lenker til json-skjema som ikke finnes: 

https://github.com/ks-no/fiks-plan-specification/blob/main/Schema/V2/no.ks.fiks.plan.v2.innsyn.plandokumenter.finn.schema.json
https://github.com/ks-no/fiks-plan-specification/blob/main/Schema/V2/no.ks.fiks.plan.v2.innsyn.plandokumenter.finn.resultat.schema.json

Tilsvarende klasser ser også ut til å mangle i nuget KS.Fiks.Plan.Models.V2 0.9.5.

**Comment by jarleborsheim** [comment]
Ja, jeg ser dette og forsøker å finne ut hva som er årsak

**Comment by jarleborsheim** [comment]
Det ser ut til at de ble slettet i denne pull-requesten: https://github.com/ks-no/fiks-plan-specification/pull/46
Som var vel en konklusjon av issuet her: https://github.com/ks-no/fiks-plan-specification/issues/32
Jeg antar at det betyr at vi må oppdatere dokumentasjonen, med mindre du vil ha disse skjemaene tilbake? @oyei

**Comment by oyei** [comment]
Ok, da vil jeg tro det holder å oppdatere dokumentasjonen.

**Comment by jarleborsheim** [comment]
Da er den dokumentasjonssiden slettet

**Comment by jarleborsheim** [comment]
Fikset og kan stenges
