### ISSUE TITLE
Spørsmål til workshop 20 mars

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-plan-specification#91]
Vi vil at dette issuet fylles med spørsmål vi ønsker å få klarert i workshop/møte 20 mars.
Møtet 20 mars skal brukes for å avklare med NPAD og dokumentere hvordan protokollen skal brukes i forskjellige tilfeller. Da kan vi også avdekke eventuelle endringer som må gjøres. 

Et mål med møtet kan også være å skille ut de tjenestene som anses som ferdig, og de som må testes ut mer. 

## Forenklet planbehandling

- Gjeldendene planident, skal den beholdes, men skiftes status?
- Ny planident for forenklet og ny plan?
- Ny plan og full behandling blir alltid ny planident
- Tydelige regler for når man kan bruke forenklet endring? Blir for mye brukt nå?

## Planbehandling

- Hvilke dokumenter **skal** overføres? De sentrale dokumentene.
- Hvordan angi at et dokument er gjeldende
- Innsyn i sak
- Tilgang til liste med url til postliste på saken. Planregister trenger å vite hvor disse dokumentene ligger.

## Registrer gjeldende planbestemmelser

- Denne tjenesten mangler. Trenger vi den? Avhengig av `planbehandling` og `forenklet planbehandling`.

## Standardisert resultat av et oppstartsmøte

**Comment by oyei** [comment]
Registrer/OppdaterDispensasjon: Skal filinnholdet for dokumentene følge med som egne payloads? 
Hvordan vet en i tilfelle hvilket dokument som gjelder for hvilken payload?

**Comment by Oreligrenda** [comment]
Innsigelse: Hvordan håndterer man at eventuelt deler av planen får forskjellig vedtaksdato pga uoppklart innsigelse.
